### ISSUE TITLE
error in console: Uncaught ReferenceError: trustedTypes is not defined

### ISSUE THREAD

**Issue by lyhistory** [filedescriptor/untrusted-types#2]
UNTRUSTED_TYPES_CHECK_STACK_BELOW:27 Uncaught ReferenceError: trustedTypes is not defined
    at UNTRUSTED_TYPES_CHECK_STACK_BELOW:27
    at UNTRUSTED_TYPES_CHECK_STACK_BELOW:36
(anonymous) @ UNTRUSTED_TYPES_CHECK_STACK_BELOW:27
(anonymous) @ UNTRUSTED_TYPES_CHECK_STACK_BELOW:36
content.js:53 Unrecognized Content-Security-Policy directive 'require-trusted-types-for'.

![image](https://user-images.githubusercontent.com/1522513/99739303-6ee1f680-2b07-11eb-9ffb-511edcd467e4.png)

![image](https://user-images.githubusercontent.com/1522513/99739287-64276180-2b07-11eb-8a3e-61b27f810cc3.png)

**Comment by filedescriptor** [comment]
You need Chrome v85+.
