### ISSUE TITLE
Keyword highlighting is not working

### ISSUE THREAD

**Issue by iambrosie** [filedescriptor/untrusted-types#4]
First of all, congrats on the impressive and creative use of Trusted Types!

I noticed, while trying to follow along your video [here](https://youtu.be/CNNCCgDkt5k?t=205), specifically the part on where you're demoing using the keyword `d0mxss` in the input field on http://prompt.ml/1, that the functionality described [here](https://github.com/filedescriptor/untrusted-types#sources---sinks) doesn't seem to be working for me.

I have no errors in my console and even tried with all other extensions disabled . 

Chrome version: 87.0.4280.67 (Official Build) (x86_64)
Untrusted-types version: 0.0.1

**Comment by filedescriptor** [comment]
Can you post the logs/screenshots?

**Comment by iambrosie** [comment]
Sure thing!

![image](https://user-images.githubusercontent.com/4072584/100389274-4426ff00-302d-11eb-99fc-80b149e692ab.png)

**Comment by filedescriptor** [comment]
Looks like for some reason it doesn't even log the change. Can you try to go to https://public-firing-range.appspot.com/address/location.hash/documentwrite#d0mxss and check the log?

**Comment by iambrosie** [comment]
Apologies for the late reply.
Here they are:

Console
![image](https://user-images.githubusercontent.com/4072584/100865088-2b887000-3497-11eb-966a-e62f71387c8a.png)
Log
![image](https://user-images.githubusercontent.com/4072584/100865156-4529b780-3497-11eb-8f45-2a31f7222ec4.png)

**Comment by iambrosie** [comment]
And below is the log for
![image](https://user-images.githubusercontent.com/4072584/100866249-aef69100-3498-11eb-828b-58c188755ff0.png)

![image](https://user-images.githubusercontent.com/4072584/100866058-6a6af580-3498-11eb-863d-29902f769547.png)

**Comment by filedescriptor** [comment]
Hmm very strange. It looks like the content script is not injected into the iframe. In fact, there doesn't seem to have sandbox.prompt.ml loaded. Mine is like below:
![contents](https://user-images.githubusercontent.com/8280340/100866539-c56e0e00-34d3-11eb-8048-d7dcfb9b82f0.png)

I noticed you are using a Mac and I think it should not be relevant, but I will try it on a Mac.

**Comment by filedescriptor** [comment]
I've tested in on a Mac and it worked as expected. I think it's most likely a prompt.ml's issue, though I can't think of one. I'll leave this issue open in case anyone experiences the same.
